version: '3.8'

services:
    app:
        image: php:8.1-fpm
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel_web
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
